export const dummyData = {
	username: 'Timantha',
	fridge: [
		{
			_id: 'dvdvv',
			name: 'burger',
			quantity: '2',
			price: 2.3,
			datePurchased: 'Sep 3rd 2021',
			useByDate: 'Sep 30th 2021',
		},
		{
			_id: 'dvdvcsdcsv',
			name: 'cumberz',
			quantity: '3 lbs',
			price: 2.3,
			datePurchased: 'Sep 5th 2021',
			useByDate: 'Oct 30th 2021',
		},
		{
			_id: 'dv2332dvv',
			name: 'sammiches',
			quantity: '4',
			price: 2.3,
			datePurchased: 'Sep 7th 2021',
			useByDate: 'Sep 25th 2021',
		},
	],
	tasted: [
		{
			_id: 'dvdvv32dw',
			name: 'sammiches',
			quantity: '4',
			price: 2.3,
			datePurchased: 'Sep 7th 2021',
			useByDate: 'Sep 25th 2021',
		},
		{
			_id: 'dvd2dsedvv32dw',
			name: 'sammiches',
			quantity: '4',
			price: 2.3,
			datePurchased: 'Sep 7th 2021',
			useByDate: 'Sep 25th 2021',
		},
	],
	wasted: [
		{
			_id: 'dvd2dsvdvvdfvedvv32dw',
			name: 'sammiches',
			quantity: '4',
			price: 2.3,
			datePurchased: 'Sep 7th 2021',
			useByDate: 'Sep 25th 2021',
		},
		{
			_id: 'dvd2ds4444vdvvdfvedvv32dw',
			name: 'sammiches',
			quantity: '4',
			price: 2.3,
			datePurchased: 'Sep 7th 2021',
			useByDate: 'Sep 25th 2021',
		},
	],
};
